# Generated by Django 4.0.4 on 2022-06-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0015_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='', max_length=50),
        ),
    ]
